### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by andk** [ingydotnet/lingy#3]
It just so happened to me that CPAN.pm died when it encountered these circular dependencies:

Recursive dependency detected:
    Lingy (have: N/A; want: 0.001004)
 => INGY/Lingy-0.1.4.tar.gz
 => YAMLTest (have: N/A; requires: 0)
 => INGY/YAMLTest-0.0.4.tar.gz
 => Test::More::YAMLScript (have: N/A; requires: v0.0.4)
 => INGY/Test-More-YAMLScript-0.1.0.tar.gz
 => YAMLScript (have: N/A; requires: v0.1.0)
 => INGY/YAMLScript-0.1.0.tar.gz
 => Lingy (have: N/A; requires: v0.1.4).
Cannot resolve.
  INGY/YAMLScript-0.1.0.tar.gz
  [depend] -- NOT OK

**Comment by ingydotnet** [comment]
Thanks for reporting this. It seems to be resolved in 0.1.11. Closing for now.
